server:
  port: 8080

spring:
  application:
    name: mini-jira-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:minijira}
    username: ${DB_USER:minijira}
    password: ${DB_PASSWORD:minijira}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
